name: news_tre
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  fluttertoast: ^8.2.4
  http: ^1.2.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.17.7
  firebase_storage: ^11.2.4
  carousel_slider: ^4.2.1
  google_fonts: ^6.2.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/login.jpeg